## 端口号 上下文路径
server:
  port: 8080
  servlet:
    context-path: /crm

## 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/crm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

  ##启用热部署
  devtools:
    restart:
      enabled: true
      additional-path: src/main/java

### mybatis
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: org.example.crm.entity
  # 原来写的configuration，得改成configuration-properties，不知道为啥
  configuration-properties:
    map-underscore-to-camel-case:true

## pageHelper分页
pagehelper:
  helper-dialect: mysql

## 设置dao日志打印级别
logging:
  level:
    org:
      example:
        crm:
          dao: debug